version: 2.1

aliases:
  - &defaults
    working_directory: /tmp/storybook
    docker:
      - image: cimg/node:16.20.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore core dependencies cache
          keys:
            - core-dependencies-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Bootstrap
          command: yarn prepareAll
      - save_cache:
          name: Cache core dependencies
          key: core-dependencies-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
            - /root/.cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

workflows:
  test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
